# Generated by Django 3.0.5 on 2020-04-30 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailystats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dbuserinfo',
            old_name='last_updateds',
            new_name='last_updated',
        ),
    ]
